Multicard compatibility changes.  (Many invocations of mas_var.)

diff --git a/script/acq_register b/script/acq_register
--- a/script/acq_register
+++ b/script/acq_register
@@ -24,9 +24,17 @@
 # note      under-used.  Passing "no_db" here suppresses db registration...
 #
 
-ARRAY_ID=`cat /data/cryo/array_id`
-LAST_TUNE=/data/cryo/last_squid_tune
-LAST_IV=/data/cryo/last_iv_det_data
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
+ARRAY_ID=`cat ${MAS_DATA_ROOT}/array_id`
+LAST_TUNE=${MAS_DATA_ROOT}/last_squid_tune
+LAST_IV=${MAS_DATA_ROOT}/last_iv_det_data
 CTIMES=/data/mce_ctimes
 
 # The record script must exist or it is not called...
diff --git a/script/check_zero b/script/check_zero
--- a/script/check_zero
+++ b/script/check_zero
@@ -22,6 +22,14 @@ if [ $# -lt 2 ]; then
     exit 127
 fi
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 card=$1
 param=$2
 quiet=$3
diff --git a/script/frameacq_stamp b/script/frameacq_stamp
--- a/script/frameacq_stamp
+++ b/script/frameacq_stamp
@@ -7,6 +7,14 @@
 #    frameacq_stamp 1 outfile 10000 | tee -a outfile.run
 #
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 source $MAS_SCRIPT/mas_library.bash
 
 runfile_version=2
@@ -27,7 +35,7 @@ fi
 data_filename="$2"
 data_framecount="$3"
 
-array_id=`cat /data/cryo/array_id`
+array_id=`cat ${MAS_DATA_ROOT}/array_id`
 mas_version=`mce_cmd -v`
 
 ctime=`date +%s`
diff --git a/script/make_idl_templates b/script/make_idl_templates
--- a/script/make_idl_templates
+++ b/script/make_idl_templates
@@ -1,6 +1,14 @@
 #!/bin/bash
 
-this_array=`cat /data/cryo/array_id`
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
+this_array=$(cat $MAS_DATA_ROOT/array_id)
 
 if [ "$this_array" == "" ] || [ "$this_array" == "default" ]; then
     expt=$MAS_CONFIG/experiment.cfg
diff --git a/script/mce_clock_mode b/script/mce_clock_mode
--- a/script/mce_clock_mode
+++ b/script/mce_clock_mode
@@ -9,6 +9,14 @@ if [ "$#" != "3" ]; then
     exit 1
 fi
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 if [ "$1" == "0" ]; then
     mce_cmd -q -X "wb cc use_dv $3" -X "wb cc use_sync $2" || exit 1
     mce_cmd -q -X "wb cc select_clk 0" || exit 1
diff --git a/script/mce_fw_update b/script/mce_fw_update
--- a/script/mce_fw_update
+++ b/script/mce_fw_update
@@ -11,6 +11,14 @@ if [ "$#" -lt "2" ]; then
     exit 1
 fi
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 function print_fw_rev {
     # Jump through some hoops to only issue fw_rev commands...
     mce_status -g | awk '($3 == "fw_rev" && $8 == "") {print $2}' | \
diff --git a/script/mce_reconfig b/script/mce_reconfig
--- a/script/mce_reconfig
+++ b/script/mce_reconfig
@@ -1,9 +1,17 @@
 #!/bin/bash
 
-CD=`cat /data/cryo/current_data_name`
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
 
-CONFIG=/data/cryo/current_data/config_mce_auto_setup_${CD}
-EXPT=/data/cryo/current_data/experiment.cfg
+CD=$(cat ${MAS_DATA_ROOT}/current_data_name)
+
+CONFIG=${MAS_DATA}/config_mce_auto_setup_${CD}
+EXPT=${MAS_DATA}/experiment.cfg
 
 if [ ! -e $CONFIG ]; then
     echo "$CONFIG not found, retune or recover manually from previous day's settings."
@@ -16,7 +24,7 @@ $CONFIG
 # Only mess with TES if tes_bias_do_reconfig=1.
 do_tes=`mas_param -s $EXPT get tes_bias_do_reconfig`
 if [ "$do_tes" == "1" ]; then
-    BIAS=/data/cryo/tes_bias_recommended
+    BIAS=${MAS_DATA_ROOT}/tes_bias_recommended
     norm_bias=`mas_param -s $EXPT get tes_bias_normal`
     norm_time=`mas_param -s $EXPT get tes_bias_normal_time`
 
diff --git a/script/mce_run b/script/mce_run
--- a/script/mce_run
+++ b/script/mce_run
@@ -8,6 +8,14 @@
 # This script is intended to be fairly low-level, it shouldn't do
 # more than it needs to to collect a complete data file.
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 source $MAS_SCRIPT/mas_library.bash
 SCRNAME=mce_run
 
diff --git a/script/mce_update_userword b/script/mce_update_userword
--- a/script/mce_update_userword
+++ b/script/mce_update_userword
@@ -4,6 +4,14 @@
 # put in 'run_id' and 'user_word' is a mix of the data mode and the
 # array_id code.
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 source $MAS_SCRIPT/mas_library.bash
 
 # Copy data mode for card $1 (eg '1' or 's') into bits 15:8
@@ -18,7 +26,7 @@ case "$1" in
 esac
 
 data_mode=`command_reply rb rc$rc data_mode`
-array_id=`cat /data/cryo/array_id`
+array_id=$(cat ${MAS_DATA_ROOT}/array_id)
 prog="(\$1==\"${array_id}\") {print \$2}"
 array_integer=`awk "${prog}" $MAS_CONFIG/array_list`
 
diff --git a/script/ramp_sa_fb b/script/ramp_sa_fb
--- a/script/ramp_sa_fb
+++ b/script/ramp_sa_fb
@@ -39,7 +39,15 @@ function runfile_loop_structure {
 # START OF MAIN ROUTINE
 #
 
-source ${MAS_SCRIPT}mas_library.bash
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
+source ${MAS_SCRIPT}/mas_library.bash
 
 if [ $# -lt 3 ]; then 
   echo "----------------" >&2
diff --git a/script/ramp_tes_bias b/script/ramp_tes_bias
--- a/script/ramp_tes_bias
+++ b/script/ramp_tes_bias
@@ -3,6 +3,14 @@
 # Adapted from ramp_tes_bias for DAS
 #
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 source $MAS_SCRIPT/mas_library.bash
 
 if [ "$#" -lt "2" ]; then
@@ -56,7 +64,7 @@ if [ "$#" -gt "7" ]; then
 fi
 
 ct=`print_ctime`
-dt=`cat /data/cryo/current_data_name`
+dt=$(cat ${MAS_DATA_ROOT}/current_data_name)
 
 data_root=$1
 n=$2
@@ -144,7 +152,7 @@ done >> $script
 
 mce_cmd -qf $script
 
-my_data=/data/cryo
+my_data=${MAS_DATA_ROOT}
 
 echo "Completed I-V acquisition!"
 
diff --git a/script/set_directory b/script/set_directory
--- a/script/set_directory
+++ b/script/set_directory
@@ -1,14 +1,22 @@
 #!/bin/bash
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 if [ "$MAS_ROOT" == "" ]; then
     echo MAS_ROOT variable not set.
     exit 1
 fi
 
-# data_root is the first argument to this function, or "/data/cryo" if
+# data_root is the first argument to this function, or $MAS_DATA_ROOT if
 # no arguments are given.
 
-data_root=${1:-"/data/cryo"}
+data_root=${1:-$MAS_DATA_ROOT}
 
 # All our new files should be group rw
 umask 002
diff --git a/script/simple_auto_wrapper b/script/simple_auto_wrapper
--- a/script/simple_auto_wrapper
+++ b/script/simple_auto_wrapper
@@ -3,6 +3,14 @@
 # Executes a script, without arguments, in an auto context.
 #
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 source $MAS_SCRIPT/mas_library.bash
 
 if [ $# -lt 1 ]; then
diff --git a/test_suite/hw_auto_cc b/test_suite/hw_auto_cc
--- a/test_suite/hw_auto_cc
+++ b/test_suite/hw_auto_cc
@@ -4,6 +4,14 @@
 # This script tests the Clock Card FPGA's hardware interfaces.
 #---------------------------------------------------------------
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 #---------------------------------------------------------------
 # CC Commands that aren't related to hardware tests:
 #---------------------------------------------------------------
diff --git a/test_suite/sram_test b/test_suite/sram_test
--- a/test_suite/sram_test
+++ b/test_suite/sram_test
@@ -17,6 +17,14 @@
 #     b) write 0x0F to detect shorts between address lines
 #   4. read back -1 from addr FFFF
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 
 let address_zero_data=0
 let "walking_one_data=0x55555555"
diff --git a/test_suite/sys_auto_mce b/test_suite/sys_auto_mce
--- a/test_suite/sys_auto_mce
+++ b/test_suite/sys_auto_mce
@@ -1,4 +1,15 @@
+#!/bin/bash
+
 # MA: no error checking here as this is temporary subrack check
+
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 source $MAS_SCRIPT/mas_library.bash
 TMP="$MAS_TEMP/mce_check.tmp"
 /bin/rm $TMP
diff --git a/test_suite/test_suite b/test_suite/test_suite
--- a/test_suite/test_suite
+++ b/test_suite/test_suite
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+#initialise environment
+if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
+  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
+  exit 1
+else
+  eval $(${MAS_VAR} -s)
+fi
+
 #---------------------------------------------------------------
 # This is the overall script for the test suite.
 #---------------------------------------------------------------
