A few tweaks to get ACT to work with python auto_setup.  Updated experiment_AR2.cfg too, but not the others.

diff --git a/script/auto_setup_squids_sh b/script/auto_setup_squids_sh
--- a/script/auto_setup_squids_sh
+++ b/script/auto_setup_squids_sh
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-## source ~mce/mas_env.bash
 source $MAS_SCRIPT/mas_library.bash
 
 short="$1"
@@ -25,10 +24,6 @@ ERRPREF="ERROR : $SCRNAME :"
 SCRIPTS=$MAS_SCRIPT
 IDL_PRO=$MAS_IDL
 
-SETUP_TARGET=99 #return value that indicates completion
-# check_bias and ramp_sa are controlled by experiment.cfg
-SETUP_IDL="auto_setup_squids,short=$short $RC"
-
 start_time=`date`
 ctime=`print_ctime`
 
@@ -36,51 +31,31 @@ echo "START : $SCRNAME : $start_time" | $LOGGER
 echo "INFO  : $SCRNAME : ctime=$ctime" | $LOGGER
 echo "ARGS  : $SCRNAME : $@" | $LOGGER
 
-# Check reset, and re-configure if detected
-#check_reset
-#if [ "$?" != "0" ]; then
-
-#    RECONFIG=$MAS_TEMPLATE/config_mce
-#    echo $ERRPREF "MCE reset detected! Running $RECONFIG" | $LOGGER
-#    $RECONFIG
-
-#    check_reset
-#    if [ "$?" != "0" ]; then
-#	echo $ERRPREF "$RECONFIG didn't help!" | $LOGGER
-#	exit 1
-#    fi
-#fi
-
 # Set observer log variable
 export MAS_LOGID="$note"
 
 # Start auto_setup
-
-cd $IDL_PRO
-idl -quiet <<EOF	
+PYTHON_TUNING=( `mas_param get python_tuning` )
+if [ "$PYTHON_TUNING" == "1" ]; then
+    note_args=
+    [ "$note" != "" ] && note_args="--reg-note \"${note}\""
+    auto_setup --shortness "$short" $note_args
+    if [ "$?" != "0" ]; then
+	echo $ERRPREF "auto_setup' returned error! [$err]" | $LOGGER
+	exit 1
+    fi
+else
+    # check_bias and ramp_sa are controlled by experiment.cfg
+    SETUP_IDL="auto_setup_squids,short=$short $RC"
+    cd $IDL_PRO
+    idl -quiet <<EOF	
 ${SETUP_IDL}
 EOF
-
-err=$?
-if [ "$err" != "$SETUP_TARGET" ]; then
-    echo $ERRPREF "'$SETUP_IDL' returned error! [$err]" | $LOGGER
-    exit 1
+    if [ "$?" != "99" ]; then
+	echo $ERRPREF "'$SETUP_IDL' returned error! [$err]" | $LOGGER
+	exit 1
+    fi
 fi
 
-err=$?
-if [ "$err" != "0" ]; then
-   echo $ERRPREF "Archiving to $ZIP_DEST failed [$err]" | $LOGGER
-   exit 1
-fi
-
-#check_reset
-#if [ "$?" != "0" ]; then
-#   echo $ERRPREF "check_reset returned positive" | $LOGGER
-#fi
-
-# Record keeping: PCI diagnostic and time elapsed
-
-# diag=`print_dsp_diagnostic`
-# echo "INFO  : $SCRNAME : $diag" | $LOGGER
 delta_ctime=`print_elapsed $ctime`
 echo "STOP  : $SCRNAME : time elapsed = $delta_ctime" | $LOGGER
