Auto-* fixes

diff --git a/script/auto_bias_step b/script/auto_bias_step
--- a/script/auto_bias_step
+++ b/script/auto_bias_step
@@ -22,36 +22,11 @@ start_ctime=`print_ctime`
 echo "START : $SCRNAME : $start_time" | $LOGGER
 echo "ARGS  : $SCRNAME : $@" | $LOGGER
 
-#Process arguments
-
-if [ "$#" != "2" ]; then
-    echo "Usage:     $SCRNAME <n_points> <log_id>"
-    echo $ERRPREF "wrong number of arguments" | $LOGGER
+mce_bias_step_acq $@
+if [ "$?" != "0" ]; then
+    echo $ERRPREF "mce_bias_step_acq returned error!" | $LOGGER
     exit 1
 fi
-
-n_frames=$1
-note="$2"
-
-# Loop over all bias lines in the system
-n_bias=`mas_param -s $MAS_DATA/experiment.cfg get bias_line_card | wc -w`
-for bias in `seq 1 $n_bias`; do
-    ACQ="bias_step_acq $bias s $n_frames"
-    ACQ_TARGET=0
-
-    this_bias=`command_reply rra tes bias $(( $bias - 1 )) 1 `
-    if [ "$this_bias" -le "0" ]; then
-	echo "INFO  : $SCRNAME : '$ACQ' suppressed because line $bias reads $this_bias."
-	continue
-    fi
-
-    export MAS_LOGID="$note"
-    $ACQ
-    if [ "$?" != "$ACQ_TARGET" ]; then
-	echo $ERRPREF "'$ACQ' returned error!" | $LOGGER
-	exit 1
-    fi
-done
 
 # Record keeping: time elapsed
 delta_ctime=`print_elapsed $start_ctime`
