Created ACT branch

diff --git a/script/bias_tess b/script/bias_tess
--- a/script/bias_tess
+++ b/script/bias_tess
@@ -1,13 +1,32 @@
 #!/bin/bash
-## source ~mce/mas_env.bash
+#
+# Applies the biases from the command line to "tes bias"
+#
+
+source $MAS_SCRIPT/mas_library.bash
+
+script_name="$0"
+bias=$1
+
 if [ $# -lt 1 ]; then
-  echo "Usage: bias_tess bias_val"
-  exit 1
+    echo "Usage: $script_name bias_val"
+    echo "The bias specified is applied to all tes bias lines."
+    exit 1
 fi
-echo "This script assumes bias_tes is on bc2! double check"
-mce_cmd -q -x wb bc2 bias $1
+
+bias_inv=`command_reply rb tes bias`
 if [ $? -ne 0 ]; then
-  echo "FAILURE: bias_tess failed!"
-  exit 2
+    echo "FAILURE : $script_name : could not read tes bias from MCE : '$bias_inv'"
+    exit 2
+fi
+
+bias_count=`echo $bias_inv | wc -w`
+bias_vals=`repeat_string $1 $bias_count`
+
+bias_output=`command_reply wb tes bias $bias_vals`
+
+if [ $? -ne 0 ]; then
+    echo "FAILURE : $script_name : could not write tes bias to MCE : '$bias_output'"
+    exit 3
 fi
 
