Removed remaining csh references.  tcsh is no longer needed to run MAS.

diff --git a/script/frameacq_stamp b/script/frameacq_stamp
--- a/script/frameacq_stamp
+++ b/script/frameacq_stamp
@@ -1,6 +1,4 @@
-#!/bin/tcsh
-#
-# why do I use csh?
+#!/bin/bash
 #
 # The output of this file should be appended to the .run file
 # Use, e.g.
@@ -9,30 +7,30 @@
 #    frameacq_stamp 1 outfile 10000 | tee -a outfile.run
 #
 
-set runfile_version=2
+runfile_version=2
 
-if ($#argv != 3) then
-  echo "Invalid frameacq_stamp arguments!  The arguments were:"
-  echo "$argv"
-  echo "Usage:\n"
-  echo "         frameacq_stamp rc_num data_filename num_frames"
-  echo
-  exit 1
-endif
+if [ $# -ne 3 ]; then
+    echo "Invalid frameacq_stamp arguments!  The arguments were:"
+    echo "$argv"
+    echo "Usage:\n"
+    echo "         frameacq_stamp rc_num data_filename num_frames"
+    echo
+    exit 1
+fi
 
-set rc="$argv[1]"
-if ( "$rc" == "s" ) then
-	set rc="1 2 3 4"
-endif
-set data_filename="$argv[2]"
-set data_framecount="$argv[3]"
+rc="$1"
+if [ "$rc" == "s" ]; then
+    rc="1 2 3 4"
+fi
+data_filename="$2"
+data_framecount="$3"
 
-set array_id=`cat /data/cryo/array_id`
-set mas_version=`mce_cmd -v`
+array_id=`cat /data/cryo/array_id`
+mas_version=`mce_cmd -v`
 
-set fileseq_on=0
-set fileseq_format=0
-set fileseq_interval=0
+fileseq_on=0
+fileseq_format=0
+fileseq_interval=0
 
 echo "<FRAMEACQ>"
 
@@ -43,10 +41,10 @@ echo "  <RC> $rc"
 echo "  <DATA_FILENAME> $data_filename"
 echo "  <DATA_FRAMECOUNT> $data_framecount"
 
-if ($fileseq_on) then
-  echo "  <FILESEQ_FORMAT> $fileseq_format"
-  echo "  <FILESEQ_INTERVAL> $fileseq_interval"
-endif
+if [ $fileseq_on -ne 0 ]; then
+    echo "  <FILESEQ_FORMAT> $fileseq_format"
+    echo "  <FILESEQ_INTERVAL> $fileseq_interval"
+fi
 
 echo "</FRAMEACQ>"
 echo
