Brought mce_run over from trunk, but without data driver locking.

diff --git a/script/mce_run b/script/mce_run
--- a/script/mce_run
+++ b/script/mce_run
@@ -1,70 +1,130 @@
-#!/bin/tcsh
-
-# Acquire data from the MCE and create or append to a .run file
+#!/bin/bash
 #
-# Run file name is obtained with script mce_runfile_name
+# Acquires data from the MCE and create or append to a .run file.
+#
+# It also writes the current unix time into the run_id word of the
+# clock card so that it appears in the frame header.
+#
+# This script is intended to be fairly low-level, it shouldn't do
+# more than it needs to to collect a complete data file.
 
-## source $MAS_ROOT/mas_env.tcsh
+source $MAS_SCRIPT/mas_library.bash
+SCRNAME=mce_run
 
-if ($#argv != 3) then
-  echo "----------------"
-  echo "Usage:              mcerun <filename> <numpts> <RC>"
-  echo ""
-  echo "     numpts   is the number of frames e.g. 24000"
-  echo "     RC       is the card number e.g. ""3"", or ""s"" for all"
-  echo "----------------"
-  exit 1
-endif
+function usage {
+    echo "Usage:              $SCRNAME <filename> <numpts> <RC> [options]"
+    echo
+    echo "     filename   is the filename; \$MAS_DATA will be prepended."
+    echo "     numpts     is the number of frames e.g. 24000"
+    echo "     RC         is the card number e.g. \"3\", or \"s\" for all"
+    echo
+    echo "Recognized options (must follow the mandatory arguments):"
+    echo "     --dirfile    force dirfile data format"
+    echo "     --flatfile   force flatfile data format"
+#    echo "     --no-locking do not check/assert the data driver lock"
+    [ "$1" == "" ] || exit $1
+    exit 1
+}
 
-set filename=$MAS_DATA/$1
-set runfilename=${filename}.run
-set numpts=$2
-set rc_num=$3
+# Defaults
 
-# This ctime won't necessarily match the filename!  But it should be
-# close and it's better than nothing.
-set ctime=`date -u +%s`
-mce_cmd -qx wb cc run_id $ctime
+acq_config_suffix=""
 
-# Re-lock
-if ("$rc_num" == "s") then
+# Three mandatory arguments
+
+[ $# -lt 3 ] && usage
+
+filename=$MAS_DATA/$1
+runfilename=${filename}.run
+numpts=$2
+rc=$3
+shift 3
+
+# Options processing
+#locking=1
+locking=0  #ACT
+
+for a in $@; do
+    case "$a" in
+	"--flatfile")
+	    acq_config_suffix=""
+	    ;;
+	
+	"--dirfile")
+	    acq_config_suffix="_dirfile"
+	    ;;
+
+	"--no-locking")
+	    locking=0
+	    ;;
+
+	*)
+	    echo "$SCRNAME : unknown option '$a'"
+	    usage
+	    ;;
+    esac
+done
+
+# Query the data lock state
+if [ "$locking" == "1" ]; then
+    if [ "$( command_reply lock_query )" == "1" ]; then
+	echo "$SCRNAME : Data lock is asserted, aborting."
+	exit 1
+    fi
+fi
+
+
+# Write current ctime into run_id location of frame header.  This
+# won't necessarily match the filename; but is better than nothing.
+# Also, put array ID code and data mode in 'user_word' field.
+
+mce_update_userword $rc
+
+# Re-initialize the servo.  Can't hurt.
+if [ "$rc" == "s" ]; then
     mce_cmd -qx wb rca flx_lp_init 1
 else
-    mce_cmd -qx wb rc$rc_num flx_lp_init 1
-endif
+    mce_cmd -qx wb rc$rc flx_lp_init 1
+fi
 
 
-#RUN FILE CREATION: NO MCE COMMANDS PAST THIS POINT
+#RUN FILE CREATION: NO MCE WRITES PAST THIS POINT
 
 echo "RUNFILE_NAME=$runfilename"
 
 # Don't remove runfile, it may have been pre-initialized
-touch $runfilename
+[ -e "$runfilename" ] || touch $runfilename
+
+# This is my favourite part.
 mce_status >> $runfilename
-if ($status) then
-  echo "mcerun: MCESTATUS action failed!"
-  exit 1
-endif
+if [ "$?" != "0" ]; then
+    echo "$SCRNAME : MCESTATUS action failed!"
+    exit 1
+fi
 
 # Apply frameacq stamp
 
-echo "# frameacq_stamp output" >> $runfilename
-frameacq_stamp $rc_num ${filename} $numpts >> $runfilename
-if ($status) then
-  echo "frameacq_stamp failed!"
-  exit 1
-endif
+frameacq_stamp $rc ${filename} $numpts >> $runfilename
+if [ "$?" != "0" ]; then
+    echo "$SCRNAME : frameacq_stamp failed!"
+    exit 1
+fi
+
+# Acquisition
 
 echo "FRAME_BASENAME=$filename"
 
-echo "acq_path /\n" \
-    "acq_config $filename rc$rc_num\n" \
-    "acq_go $numpts" | mce_cmd -q
+lock_opts=
+[ "$locking" == "1" ] && lock_opts="-X lock_down"
 
-if ($status) then
-  echo "mce_cmd failed to start acquisition."
-  exit 1
-endif
+mce_cmd -q -o / \
+    $lock_opts \
+    -X "acq_config${acq_config_suffix} $filename rc$rc" \
+    -X "acq_go $numpts"
+
+if [ "$?" != "0" ]; then
+    echo "$SCRNAME : mce_cmd returned error"
+    exit 1
+fi
 
 exit 0
-
