Check if runfile exists.

diff --git a/script/mce_raw_acq b/script/mce_raw_acq
--- a/script/mce_raw_acq
+++ b/script/mce_raw_acq
@@ -33,6 +33,7 @@ if [ "$5" == "no_runfile" ]; then
     do_runfile=0
 else
     do_runfile=1
+    [ -e $runfilename ] && echo "Error: $runfilename already exists" && exit 1
 fi
 
 rc_cmd=$rc
diff --git a/script/mce_raw_acq_1col b/script/mce_raw_acq_1col
--- a/script/mce_raw_acq_1col
+++ b/script/mce_raw_acq_1col
@@ -60,6 +60,7 @@ if [ "$6" == "no_runfile" ]; then
     do_runfile=0
 else
     do_runfile=1
+    [ -e $runfilename ] && echo "Error: $runfilename already exists" && exit 1
 fi
 
 # Disable sync box
