Fix auto_iv and mce_reconfig to handle last_iv.out link correctly.

diff --git a/script/mce_reconfig b/script/mce_reconfig
--- a/script/mce_reconfig
+++ b/script/mce_reconfig
@@ -24,9 +24,16 @@ echo Running $CONFIG
 $CONFIG || exit 1
 
 # Only mess with TES if tes_bias_do_reconfig=1.
-do_tes=`mas_param -s $EXPT get tes_bias_do_reconfig`
+do_tes=`mas_param -s $EXPT get tes_bias_do_reconfig | sed 's/\ //g'`
+echo x${do_tes}x
 if [ "$do_tes" == "1" ]; then
-    BIAS=${MAS_DATA_ROOT}/tes_bias_recommended
+    last_iv=${MAS_DATA_ROOT}/last_iv.out
+    echo $last_iv
+    if ! [ -e $last_iv ]; then
+	echo Could not find last IV analysis file $last_iv 
+	exit 1
+    fi
+    #BIAS=${MAS_DATA_ROOT}/tes_bias_recommended
     norm_bias=`mas_param -s $EXPT get tes_bias_normal`
     norm_time=`mas_param -s $EXPT get tes_bias_normal_time`
 
@@ -34,5 +41,8 @@ if [ "$do_tes" == "1" ]; then
     bias_tess $norm_bias
     sleep $norm_time
     echo Biasing tes to recommended values.
-    $BIAS
+    auto_iv bias $last_iv || ( \
+	echo "auto_iv failed to set bias."
+	exit 1
+    )
 fi
