Bashify mce_fw_update a bit, fix path bug.

diff --git a/script/mce_fw_update b/script/mce_fw_update
--- a/script/mce_fw_update
+++ b/script/mce_fw_update
@@ -16,29 +16,36 @@ JAM_DIR=$MCE_JAM_DIR
 JAM_FILE=$2
 START_TIME=`date +%s`
 
-if ! echo $JAM_FILE | grep -q '^/'; then
-  JAM_FILE=$JAM_DIR/$JAM_FILE
+if ! [ -r $JAM_FILE ] && [ "$JAM_DIR" != "" ]; then
+    echo "File not found in current directory, looking in $JAM_DIR"
+    JAM_FILE=$JAM_DIR/$JAM_FILE
 fi
 
-if [ ! -r $JAM_FILE ]; then
-  echo "Error: cannot read $JAM_FILE"
+if ! [ -r $JAM_FILE ]; then
+  echo "Error: cannot find $2"
   echo
   exit 1
 fi
 
 echo " MCE firmware revisions prior to firmware update:"
-mce_status -s |grep fw_rev
+#mce_status -s |grep fw_rev
 
-if [[ $DEVICE == "EPC16" ]]; then
-  mce_jam -u -f800000 -aprogram -dDO_VERIFY=0 $JAM_FILE
-elif [[ $DEVICE == "EPCS64" ]]; then
-  mce_jam -u -f8000000 -aconfigure $JAM_FILE
-  mce_jam -u -f100000 -aprogram -dDO_VERIFY=0 $JAM_FILE
-elif [[ $DEVICE == "FPGA" ]]; then
-  mce_jam -u -f8000000 -aconfigure $JAM_FILE
-else
-  echo "  Error: device=$DEVICE is not a valid device. Use FPGA or EPC16 or EPCS64 to specify the device"
-fi
+case "$DEVICE" in
+    EPC16)
+	echo mce_jam -u -f800000 -aprogram -dDO_VERIFY=0 $JAM_FILE
+	;;
+    EPCS64)
+	mce_jam -u -f8000000 -aconfigure $JAM_FILE && \
+	    mce_jam -u -f100000 -aprogram -dDO_VERIFY=0 $JAM_FILE
+	;;
+    FPGA)
+	mce_jam -u -f8000000 -aconfigure $JAM_FILE
+	;;
+    *)
+	echo "Error: device=$DEVICE is not a valid device."
+	echo "  Use FPGA or EPC16 or EPCS64 to specify the device"
+	;;
+esac
 
 echo " Configuration complete."
 
@@ -49,9 +56,9 @@ if [[ $DEVICE != "FPGA"  ]]; then
 fi
 
 echo "  Reset PCI card and MCE.."
-`mce_cmd -q -x dsp_reset`
+mce_cmd -q -x dsp_reset
 sleep 2
-`mce_cmd -q -x mce_reset`
+mce_cmd -q -x mce_reset
 sleep 2
 
 echo "  Firmware revisions after firmware update:"
