compare rc readback results with fb_const settings and report PASS/FAIL.

diff --git a/test_suite/sys_auto_mce b/test_suite/sys_auto_mce
--- a/test_suite/sys_auto_mce
+++ b/test_suite/sys_auto_mce
@@ -1,6 +1,6 @@
 # MA: no error checking here as this is temporary subrack check
 source $MAS_SCRIPT/mas_library.bash
-TMP="$MAS_TEMP/$0.tmp"
+TMP="$MAS_TEMP/mce_check.tmp"
 
 today=`date`
 echo "$0 run under MAS on $today"
@@ -24,7 +24,7 @@ done
 # report power status
 psc_status
 
-# take data and compare results
+# set column data to column number, read back the data and compare results
 /bin/rm $MAS_DATA/.tmp.data
 echo "wb rca sample_num 1">$TMP
 echo "wb rca data_mode 1">>$TMP
@@ -32,10 +32,20 @@ echo "wb rc1 fb_const 1 2 3 4 5 6 7 8">>$TMP
 echo "wb rc2 fb_const 9 10 11 12 13 14 15 16">>$TMP
 echo "wb rc3 fb_const 17 18 19 20 21 22 23 24">>$TMP
 echo "wb rc4 fb_const 25 26 27 28 29 30 31 32">>$TMP
-echo "acq_config $MAS_DATA/.tmp.data rcs">>$TMP
-echo "acq_go 1">>$TMP
+#echo "acq_config $MAS_DATA/.tmp.data rcs">>$TMP
+#echo "acq_go 1">>$TMP
 mce_cmd -q -f $TMP
-for i in `seq 1 1`; do 
-  a=`ascii_frame 41 32 $MAS_DATA/.tmp.data 0 "%8i"|awk 'NF==32 {print $\$i}'`
-  #echo $a
+
+# take 1 frame of data
+mce_run .tmp.data 1 s
+ 
+for column in `seq 1 32`; do 
+  a=`ascii_frame 41 32 $MAS_DATA/.tmp.data 0 "%8i"|awk 'NF==32 {print $'$column'}'`
+  column_data=`echo $a|awk '{printf "%d ", $1}'`
+  if [ $column_data != $column ]; then
+    echo "Column data readback Test Failed!"
+    exit 1
+  fi 
 done
+echo "MCE information collected and simple data acquisition test Passed!"
+
